# Додаткові завдання №3

## 1 Перевірка взаємної простоти двох чисел
Реалізуйте алгоритм Евкліда для перевірки взаємної простоти двох чисел (у вигляді функції від двох аргументів).
Виконайте друге завдання з **Домашньої роботи №3** (**Задача 1.3.14**) з використанням даної функції.

In [2]:
# Місце для Вашого коду
from itertools import combinations
import numpy as np
def Evklid (a, b):
    x=a
    y=b
    while y!=0:
        x, y=y, x%y
    print(x)
    return(x==1)


def teor (n, k, p, q):
    if Evklid (p,q):
        my_range=range(1,n+1)
        choose_k = list(combinations(my_range,k))
        n1, n2, n3=0, 0, 0
        d=len(choose_k)
        for i in choose_k:
            Flag1=True
            Flag2=True
            Flag3=False
            for j in i:
                if j%p==0:
                    Flag3=True
                elif j%q==0:
                    Flag1=False
                else:
                    Flag1=False
                    Flag2=False
            n1+=Flag1
            n2+=Flag2
            n3+=Flag3
        print ('кожне з вибраних чисел кратне даному числу  𝑝: {};  кожне з вибраних чисел кратне хоча б одному з двох взаємно простих чисел  𝑝  i  𝑞 :{}; серед вибраних чисел є хоча б одне кратне  𝑝 :{}'.format(n1/d, n2/d, n3/d)) 
    else:
        print(p, q, 'не взаємнопрості')
teor(𝑛=25,𝑘=5,𝑝=3,𝑞=4) 
teor(𝑛=25,𝑘=10,𝑝=3,𝑞=4) 
teor(𝑛=25,𝑘=10,𝑝=30,𝑞=40) 

def emp (n, k, p, q):
    if Evklid (p,q):
        my_range=range(1,n+1)
        choose_k =[]
        for i in range(10000):
            choose_k.append(list(np.random.choice(my_range, size=k, replace=False)))
        n1, n2, n3=0, 0, 0
        d=len(choose_k)
        for i in choose_k:
            Flag1=True
            Flag2=True
            Flag3=False
            for j in i:
                if j%p==0:
                    Flag3=True
                elif j%q==0:
                    Flag1=False
                else:
                    Flag1=False
                    Flag2=False
            n1+=Flag1
            n2+=Flag2
            n3+=Flag3
        print ('кожне з вибраних чисел кратне даному числу  𝑝: {};  кожне з вибраних чисел кратне хоча б одному з двох взаємно простих чисел  𝑝  i  𝑞 :{}; серед вибраних чисел є хоча б одне кратне  𝑝 :{}'.format(n1/d, n2/d, n3/d)) 
    else:
        print(p, q, 'не взаємнопрості')
emp(𝑛=25,𝑘=5,𝑝=3,𝑞=4) 
emp(𝑛=25,𝑘=10,𝑝=3,𝑞=4) 
emp(𝑛=25,𝑘=10,𝑝=30,𝑞=40) 

1
кожне з вибраних чисел кратне даному числу  𝑝: 0.001054018445322793;  кожне з вибраних чисел кратне хоча б одному з двох взаємно простих чисел  𝑝  i  𝑞 :0.014906832298136646; серед вибраних чисел є хоча б одне кратне  𝑝 :0.8835309617918313
1
кожне з вибраних чисел кратне даному числу  𝑝: 0.0;  кожне з вибраних чисел кратне хоча б одному з двох взаємно простих чисел  𝑝  i  𝑞 :2.0191142818683536e-05; серед вибраних чисел є хоча б одне кратне  𝑝 :0.9940503432494279
10
30 40 не взаємнопрості
1
кожне з вибраних чисел кратне даному числу  𝑝: 0.0018;  кожне з вибраних чисел кратне хоча б одному з двох взаємно простих чисел  𝑝  i  𝑞 :0.0166; серед вибраних чисел є хоча б одне кратне  𝑝 :0.8792
1
кожне з вибраних чисел кратне даному числу  𝑝: 0.0;  кожне з вибраних чисел кратне хоча б одному з двох взаємно простих чисел  𝑝  i  𝑞 :0.0; серед вибраних чисел є хоча б одне кратне  𝑝 :0.9933
10
30 40 не взаємнопрості


## 2 Аналіз функцій з класу *numpy.random*
Проаналізуйте взаємозв'язок між функціями з класу **numpy.random**:
- [rand](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.rand.html)
- [randint](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.randint.html)
- [random_integers](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random_integers.html)
- [random_sample](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random_sample.html)
- [random](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.random.html)
- [ranf](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.ranf.html)
- [sample](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.sample.html)
- [choice](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.choice.html)
- [shuffle](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.shuffle.html)
- [permutation](https://docs.scipy.org/doc/numpy-1.14.1/reference/generated/numpy.random.permutation.html)

In [41]:
# Місце для Вашого коду та висновків
import numpy.random
print ('rand', numpy.random.rand (2, 3, 4)) #повертає масив розміру 2*3*4 (аргументи функції) - з чисел від 0 до 1
x1=numpy.random.randint (1, 10, size=(2, 3, 4))
print ('randint', type(x1[0, 0, 0]), x1) #повертає масив розміру 2*3*4 (size) - з чисел від 1 до 9 (від першого аргументу до другого)
x2=numpy.random.random_integers (1, 10, size=(2, 3, 4))# робить теж саме, але другий параметр включно, а якщо другого параметру нема, бере числа від 1 до першого параметру(включно. 

print ('random_integers', type(x2[0, 0, 0]), x2) #повертає масив розміру 2*3*4 (size) - з чисел від 1 до 9 (від першого аргументу до другого)
shape=(2, 3, 4)
print('sample', np.random.random_sample(shape))#подібна до random.rand, але приймає в якості параметрів не довільну кількість цілих чисел, а одразу кортеж з них
shape=(2, 3, 4)
print('random', np.random.random(shape))#Еквівалентна до np.random.random_sample. Подібна до random.rand, але приймає в якості параметрів не довільну кількість цілих чисел, а одразу кортеж з них
shape=(2, 3, 4)
print('ranf', np.random.ranf(shape))#Еквівалентна до np.random.random_sample. Подібна до random.rand, але приймає в якості параметрів не довільну кількість цілих чисел, а одразу кортеж з них
shape=(2, 3, 4)
print('sample', np.random.sample(shape))#Еквівалентна до np.random.random_sample. Подібна до random.rand, але приймає в якості параметрів не довільну кількість цілих чисел, а одразу кортеж з них
shape=(2, 3, 4)
A=range(10)
p=[0.02, 0.1, 0.05, 0.05, 0.2, 0.15, 0.025, 0.025, 0.37, 0.01]
print('choice', np.random.choice(A, shape, replace=True, p=p))#Обирає з першого аргументу - об'єкта типу, що ітерується, масив розмірів shape.
#Якщо replace=True, то об'єкти з А можуть входити в новий масив декілька разів. Останній аргумент - це ймовірності кожної з подій довжина р має дорівнювати довжині А
arr = np.arange(10)
print('before np.random.shuffle'+str(arr))
(np.random.shuffle(arr))#перемішує перший аргумент - об'єкт типу, що ітерується. Нічого не повертає, але arr вже перемішаний
print('after np.random.shuffle'+str(arr))
print(numpy.random.permutation(7))#якщо аргумент numpy.random.permutation - число, то повертає перемішану послідовність від 0 до аргументу (не включно)
a=[1,7,2]
print('numpy.random.permutation', numpy.random.permutation(a)) #якщо аргумент numpy.random.permutation - об'єкта типу, що ітерується, то повертає перемішану КОПІЮ цього об'єкту

print(a)

rand [[[0.65773978 0.38480526 0.48446976 0.64584276]
  [0.18973651 0.50620192 0.11427503 0.47995162]
  [0.23974077 0.23751408 0.4329827  0.99249548]]

 [[0.55358065 0.6351244  0.64822707 0.08295776]
  [0.27171082 0.2771419  0.5460812  0.98312599]
  [0.44178363 0.60215805 0.39642485 0.0519866 ]]]
randint <class 'numpy.int32'> [[[5 6 3 1]
  [4 8 7 1]
  [5 6 1 7]]

 [[5 4 7 4]
  [7 9 2 9]
  [2 1 5 6]]]
random_integers <class 'numpy.int32'> [[[ 5 10  7  5]
  [ 2  6  2  5]
  [10 10  7  7]]

 [[10 10  9  9]
  [ 4  4 10  6]
  [ 5  4  2  2]]]
sample [[[0.95296771 0.0249558  0.65335436 0.9311015 ]
  [0.62224346 0.57510672 0.36315144 0.53133384]
  [0.3184186  0.1548044  0.4299814  0.885576  ]]

 [[0.15578068 0.25711467 0.61752575 0.60408216]
  [0.92778551 0.411481   0.47445193 0.20727943]
  [0.84878455 0.54651137 0.0124046  0.30057725]]]
random [[[0.80500817 0.49732352 0.46259688 0.27153548]
  [0.78242871 0.99376282 0.46924642 0.80855721]
  [0.14593132 0.99256841 0.77332026 0.75379933]]

 [[0.54

E:\Anaconda\lib\site-packages\ipykernel_launcher.py:6: DeprecationWarning: This function is deprecated. Please call randint(1, 10 + 1) instead
  
